from collections.abc import Hashable

import numpy as np
from anytree import NodeMixin

from ..typing import Array

class Node(NodeMixin):
    def __init__(
        self,
        node_id: int,
        *,
        feature: Hashable | None = None,
        value: np.ndarray[tuple[int, ...], np.dtype[np.float64]] | None = None,
        parent: Node | None = None,
        threshold: float | None = None,
        code: Hashable | None = None,
        left: Node | None = None,
        right: Node | None = None,
    ) -> None: ...
    @property
    def feature(self) -> Hashable: ...
    @property
    def value(self) -> Array: ...
    @property
    def threshold(self) -> float: ...
    @property
    def code(self) -> Hashable: ...
    @property
    def node_id(self) -> int: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def size(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def parent(self) -> Node: ...
    @parent.setter
    def parent(self, value: Node | None) -> None: ...
    @parent.deleter
    def parent(self) -> None: ...
    @property
    def children(self) -> tuple[Node, ...]: ...
    @children.setter
    def children(self, children: tuple[Node, ...]) -> None: ...
    @children.deleter
    def children(self) -> None: ...
    @property
    def leaves(self) -> tuple[Node, ...]: ...
    @property
    def left(self) -> Node: ...
    @left.setter
    def left(self, node: Node) -> None: ...
    @property
    def right(self) -> Node: ...
    @right.setter
    def right(self, node: Node) -> None: ...
