# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Moises\Documents\GitHub\OCEAN\ui\uiIterable\CounterfactualInterface\CounterfactualIterable\Iteration\Iteration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Iteration(object):
    def setupUi(self, Iteration):
        Iteration.setObjectName("Iteration")
        Iteration.resize(904, 366)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Iteration)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetContainerGraph = QtWidgets.QWidget(Iteration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetContainerGraph.sizePolicy().hasHeightForWidth())
        self.widgetContainerGraph.setSizePolicy(sizePolicy)
        self.widgetContainerGraph.setStyleSheet("QWidget [objectName*=\"widgetContainerGraph\"]{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.widgetContainerGraph.setObjectName("widgetContainerGraph")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetContainerGraph)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSelectFeaturesToPlot = QtWidgets.QLabel(self.widgetContainerGraph)
        self.labelSelectFeaturesToPlot.setMinimumSize(QtCore.QSize(0, 25))
        self.labelSelectFeaturesToPlot.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelSelectFeaturesToPlot.setObjectName("labelSelectFeaturesToPlot")
        self.verticalLayout_2.addWidget(self.labelSelectFeaturesToPlot)
        self.widgetContainerAxes = QtWidgets.QWidget(self.widgetContainerGraph)
        self.widgetContainerAxes.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widgetContainerAxes.setObjectName("widgetContainerAxes")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widgetContainerAxes)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.comboBoxCheckable = CheckableComboBox(self.widgetContainerAxes)
        self.comboBoxCheckable.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxCheckable.setObjectName("comboBoxCheckable")
        self.horizontalLayout_9.addWidget(self.comboBoxCheckable)
        self.pushButtonUpdateGraph = QtWidgets.QPushButton(self.widgetContainerAxes)
        self.pushButtonUpdateGraph.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonUpdateGraph.setObjectName("pushButtonUpdateGraph")
        self.horizontalLayout_9.addWidget(self.pushButtonUpdateGraph)
        self.verticalLayout_2.addWidget(self.widgetContainerAxes)
        self.widgetContainer = QtWidgets.QWidget(self.widgetContainerGraph)
        self.widgetContainer.setObjectName("widgetContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widgetContainer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widgetCanvas = MatplotLibCanvas(self.widgetContainer)
        self.widgetCanvas.setObjectName("widgetCanvas")
        self.horizontalLayout_3.addWidget(self.widgetCanvas)
        self.widgetContainerFeatureInformations = QtWidgets.QWidget(self.widgetContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetContainerFeatureInformations.sizePolicy().hasHeightForWidth())
        self.widgetContainerFeatureInformations.setSizePolicy(sizePolicy)
        self.widgetContainerFeatureInformations.setMinimumSize(QtCore.QSize(310, 0))
        self.widgetContainerFeatureInformations.setMaximumSize(QtCore.QSize(310, 16777215))
        self.widgetContainerFeatureInformations.setStyleSheet("QWidget [objectName*=\"widgetContainerGraph\"]{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.widgetContainerFeatureInformations.setObjectName("widgetContainerFeatureInformations")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetContainerFeatureInformations)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelFeatureInformations = QtWidgets.QLabel(self.widgetContainerFeatureInformations)
        self.labelFeatureInformations.setMinimumSize(QtCore.QSize(0, 25))
        self.labelFeatureInformations.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelFeatureInformations.setObjectName("labelFeatureInformations")
        self.verticalLayout_3.addWidget(self.labelFeatureInformations)
        self.listWidgetFeatureInformations = QtWidgets.QListWidget(self.widgetContainerFeatureInformations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetFeatureInformations.sizePolicy().hasHeightForWidth())
        self.listWidgetFeatureInformations.setSizePolicy(sizePolicy)
        self.listWidgetFeatureInformations.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidgetFeatureInformations.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidgetFeatureInformations.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidgetFeatureInformations.setObjectName("listWidgetFeatureInformations")
        self.verticalLayout_3.addWidget(self.listWidgetFeatureInformations)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.labelFeatureDistribution = QtWidgets.QLabel(self.widgetContainerFeatureInformations)
        self.labelFeatureDistribution.setMinimumSize(QtCore.QSize(0, 25))
        self.labelFeatureDistribution.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelFeatureDistribution.setObjectName("labelFeatureDistribution")
        self.verticalLayout_3.addWidget(self.labelFeatureDistribution)
        self.widgetCanvasDistribution = MatplotLibCanvasDistribution(self.widgetContainerFeatureInformations)
        self.widgetCanvasDistribution.setMinimumSize(QtCore.QSize(0, 240))
        self.widgetCanvasDistribution.setMaximumSize(QtCore.QSize(16777215, 240))
        self.widgetCanvasDistribution.setObjectName("widgetCanvasDistribution")
        self.verticalLayout_3.addWidget(self.widgetCanvasDistribution)
        self.horizontalLayout_3.addWidget(self.widgetContainerFeatureInformations)
        self.verticalLayout_2.addWidget(self.widgetContainer)
        self.widgetNextFinish = QtWidgets.QWidget(self.widgetContainerGraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetNextFinish.sizePolicy().hasHeightForWidth())
        self.widgetNextFinish.setSizePolicy(sizePolicy)
        self.widgetNextFinish.setObjectName("widgetNextFinish")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetNextFinish)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonNext = QtWidgets.QPushButton(self.widgetNextFinish)
        self.pushButtonNext.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.horizontalLayout_2.addWidget(self.pushButtonNext)
        self.pushButtonFinish = QtWidgets.QPushButton(self.widgetNextFinish)
        self.pushButtonFinish.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonFinish.setObjectName("pushButtonFinish")
        self.horizontalLayout_2.addWidget(self.pushButtonFinish)
        self.verticalLayout_2.addWidget(self.widgetNextFinish)
        self.horizontalLayout.addWidget(self.widgetContainerGraph)

        self.retranslateUi(Iteration)
        QtCore.QMetaObject.connectSlotsByName(Iteration)

    def retranslateUi(self, Iteration):
        _translate = QtCore.QCoreApplication.translate
        Iteration.setWindowTitle(_translate("Iteration", "Form"))
        self.labelSelectFeaturesToPlot.setText(_translate("Iteration", "Select Features To Plot"))
        self.pushButtonUpdateGraph.setText(_translate("Iteration", "Update Graph"))
        self.labelFeatureInformations.setText(_translate("Iteration", "Feature Informations"))
        self.labelFeatureDistribution.setText(_translate("Iteration", "Feature Distribution"))
        self.pushButtonNext.setText(_translate("Iteration", "Next"))
        self.pushButtonFinish.setText(_translate("Iteration", "Finish"))
from Canvas.MatplotLibCanvas import MatplotLibCanvas
from Canvas.MatplotLibCanvasDistribution import MatplotLibCanvasDistribution
from CounterfactualInterface.CheckableComboBox.CheckableComboBox import CheckableComboBox
