# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Moises\Documents\GitHub\OCEAN\ui\CounterfactualInterface\CounterfactualIterable\Iteration\Iteration.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Iteration(object):
    def setupUi(self, Iteration):
        Iteration.setObjectName("Iteration")
        Iteration.resize(904, 362)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Iteration)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetContainerDataset = QtWidgets.QWidget(Iteration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetContainerDataset.sizePolicy().hasHeightForWidth())
        self.widgetContainerDataset.setSizePolicy(sizePolicy)
        self.widgetContainerDataset.setMinimumSize(QtCore.QSize(340, 0))
        self.widgetContainerDataset.setMaximumSize(QtCore.QSize(340, 16777215))
        self.widgetContainerDataset.setStyleSheet("QWidget [objectName*=\"widgetContainerDataset\"]{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.widgetContainerDataset.setObjectName("widgetContainerDataset")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetContainerDataset)
        self.verticalLayout_3.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelAdjustConstraints = QtWidgets.QLabel(self.widgetContainerDataset)
        self.labelAdjustConstraints.setMinimumSize(QtCore.QSize(0, 25))
        self.labelAdjustConstraints.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelAdjustConstraints.setObjectName("labelAdjustConstraints")
        self.verticalLayout_3.addWidget(self.labelAdjustConstraints)
        self.listWidgetSelectedPoint = QtWidgets.QListWidget(self.widgetContainerDataset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetSelectedPoint.sizePolicy().hasHeightForWidth())
        self.listWidgetSelectedPoint.setSizePolicy(sizePolicy)
        self.listWidgetSelectedPoint.setObjectName("listWidgetSelectedPoint")
        self.verticalLayout_3.addWidget(self.listWidgetSelectedPoint)
        self.labelCurrentClass = QtWidgets.QLabel(self.widgetContainerDataset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCurrentClass.sizePolicy().hasHeightForWidth())
        self.labelCurrentClass.setSizePolicy(sizePolicy)
        self.labelCurrentClass.setMinimumSize(QtCore.QSize(0, 25))
        self.labelCurrentClass.setObjectName("labelCurrentClass")
        self.verticalLayout_3.addWidget(self.labelCurrentClass)
        self.horizontalLayout.addWidget(self.widgetContainerDataset)
        self.widgetContainerGraph = QtWidgets.QWidget(Iteration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetContainerGraph.sizePolicy().hasHeightForWidth())
        self.widgetContainerGraph.setSizePolicy(sizePolicy)
        self.widgetContainerGraph.setStyleSheet("QWidget [objectName*=\"widgetContainerGraph\"]{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.widgetContainerGraph.setObjectName("widgetContainerGraph")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetContainerGraph)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSelectFeaturesToPlot = QtWidgets.QLabel(self.widgetContainerGraph)
        self.labelSelectFeaturesToPlot.setMinimumSize(QtCore.QSize(0, 25))
        self.labelSelectFeaturesToPlot.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelSelectFeaturesToPlot.setObjectName("labelSelectFeaturesToPlot")
        self.verticalLayout_2.addWidget(self.labelSelectFeaturesToPlot)
        self.widgetContainerAxes = QtWidgets.QWidget(self.widgetContainerGraph)
        self.widgetContainerAxes.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widgetContainerAxes.setObjectName("widgetContainerAxes")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widgetContainerAxes)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.comboBoxCheckable = CheckableComboBox(self.widgetContainerAxes)
        self.comboBoxCheckable.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxCheckable.setObjectName("comboBoxCheckable")
        self.horizontalLayout_9.addWidget(self.comboBoxCheckable)
        self.pushButtonUpdateGraph = QtWidgets.QPushButton(self.widgetContainerAxes)
        self.pushButtonUpdateGraph.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonUpdateGraph.setObjectName("pushButtonUpdateGraph")
        self.horizontalLayout_9.addWidget(self.pushButtonUpdateGraph)
        self.verticalLayout_2.addWidget(self.widgetContainerAxes)
        self.widgetContainerCanvas = MatplotLibCanvas(self.widgetContainerGraph)
        self.widgetContainerCanvas.setObjectName("widgetContainerCanvas")
        self.verticalLayout_2.addWidget(self.widgetContainerCanvas)
        self.widgetNextFinish = QtWidgets.QWidget(self.widgetContainerGraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetNextFinish.sizePolicy().hasHeightForWidth())
        self.widgetNextFinish.setSizePolicy(sizePolicy)
        self.widgetNextFinish.setObjectName("widgetNextFinish")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetNextFinish)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonNext = QtWidgets.QPushButton(self.widgetNextFinish)
        self.pushButtonNext.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.horizontalLayout_2.addWidget(self.pushButtonNext)
        self.pushButtonFinish = QtWidgets.QPushButton(self.widgetNextFinish)
        self.pushButtonFinish.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonFinish.setObjectName("pushButtonFinish")
        self.horizontalLayout_2.addWidget(self.pushButtonFinish)
        self.verticalLayout_2.addWidget(self.widgetNextFinish)
        self.horizontalLayout.addWidget(self.widgetContainerGraph)

        self.retranslateUi(Iteration)
        QtCore.QMetaObject.connectSlotsByName(Iteration)

    def retranslateUi(self, Iteration):
        _translate = QtCore.QCoreApplication.translate
        Iteration.setWindowTitle(_translate("Iteration", "Form"))
        self.labelAdjustConstraints.setText(_translate("Iteration", "Adjust Constraints"))
        self.labelCurrentClass.setText(_translate("Iteration", "Current Class:"))
        self.labelSelectFeaturesToPlot.setText(_translate("Iteration", "Select Features To Plot"))
        self.pushButtonUpdateGraph.setText(_translate("Iteration", "Update Graph"))
        self.pushButtonNext.setText(_translate("Iteration", "Next"))
        self.pushButtonFinish.setText(_translate("Iteration", "Finish"))
from Canvas.MatplotLibCanvas import MatplotLibCanvas
from CounterfactualInterface.CheckableComboBox.CheckableComboBox import CheckableComboBox
