# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Moises\Documents\GitHub\INF2102\CounterfactualInterface\LineEditMinimumMaximum\LineEditMinimumMaximum.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LineEditMinimumMaximum(object):
    def setupUi(self, LineEditMinimumMaximum):
        LineEditMinimumMaximum.setObjectName("LineEditMinimumMaximum")
        LineEditMinimumMaximum.resize(500, 105)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LineEditMinimumMaximum.sizePolicy().hasHeightForWidth())
        LineEditMinimumMaximum.setSizePolicy(sizePolicy)
        LineEditMinimumMaximum.setMaximumSize(QtCore.QSize(500, 105))
        self.gridLayout = QtWidgets.QGridLayout(LineEditMinimumMaximum)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditMaximumValue = QtWidgets.QLineEdit(LineEditMinimumMaximum)
        self.lineEditMaximumValue.setEnabled(False)
        self.lineEditMaximumValue.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditMaximumValue.setObjectName("lineEditMaximumValue")
        self.gridLayout.addWidget(self.lineEditMaximumValue, 2, 4, 1, 1)
        self.lineEditMinimumInputValue = QtWidgets.QLineEdit(LineEditMinimumMaximum)
        self.lineEditMinimumInputValue.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditMinimumInputValue.setObjectName("lineEditMinimumInputValue")
        self.gridLayout.addWidget(self.lineEditMinimumInputValue, 1, 5, 1, 1)
        self.labelFeatureMaximumValue = QtWidgets.QLabel(LineEditMinimumMaximum)
        self.labelFeatureMaximumValue.setMinimumSize(QtCore.QSize(0, 25))
        self.labelFeatureMaximumValue.setObjectName("labelFeatureMaximumValue")
        self.gridLayout.addWidget(self.labelFeatureMaximumValue, 2, 3, 1, 1)
        self.lineEditMinimumValue = QtWidgets.QLineEdit(LineEditMinimumMaximum)
        self.lineEditMinimumValue.setEnabled(False)
        self.lineEditMinimumValue.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditMinimumValue.setObjectName("lineEditMinimumValue")
        self.gridLayout.addWidget(self.lineEditMinimumValue, 1, 4, 1, 1)
        self.lineEditMaximumInputValue = QtWidgets.QLineEdit(LineEditMinimumMaximum)
        self.lineEditMaximumInputValue.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditMaximumInputValue.setObjectName("lineEditMaximumInputValue")
        self.gridLayout.addWidget(self.lineEditMaximumInputValue, 2, 5, 1, 1)
        self.lineEditUserValue = QtWidgets.QLineEdit(LineEditMinimumMaximum)
        self.lineEditUserValue.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditUserValue.setObjectName("lineEditUserValue")
        self.gridLayout.addWidget(self.lineEditUserValue, 1, 1, 1, 1)
        self.labelFeatureUserValue = QtWidgets.QLabel(LineEditMinimumMaximum)
        self.labelFeatureUserValue.setMinimumSize(QtCore.QSize(0, 25))
        self.labelFeatureUserValue.setObjectName("labelFeatureUserValue")
        self.gridLayout.addWidget(self.labelFeatureUserValue, 1, 0, 1, 1)
        self.labelFeatureMinimumValue = QtWidgets.QLabel(LineEditMinimumMaximum)
        self.labelFeatureMinimumValue.setMinimumSize(QtCore.QSize(0, 25))
        self.labelFeatureMinimumValue.setObjectName("labelFeatureMinimumValue")
        self.gridLayout.addWidget(self.labelFeatureMinimumValue, 1, 3, 1, 1)
        self.labelSpacer = QtWidgets.QLabel(LineEditMinimumMaximum)
        self.labelSpacer.setMinimumSize(QtCore.QSize(70, 25))
        self.labelSpacer.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"}")
        self.labelSpacer.setText("")
        self.labelSpacer.setObjectName("labelSpacer")
        self.gridLayout.addWidget(self.labelSpacer, 1, 2, 1, 1)
        self.labelFeatureName = QtWidgets.QLabel(LineEditMinimumMaximum)
        self.labelFeatureName.setMinimumSize(QtCore.QSize(0, 25))
        self.labelFeatureName.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"}")
        self.labelFeatureName.setText("")
        self.labelFeatureName.setObjectName("labelFeatureName")
        self.gridLayout.addWidget(self.labelFeatureName, 0, 0, 1, 4)
        self.checkBoxActionability = QtWidgets.QCheckBox(LineEditMinimumMaximum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxActionability.sizePolicy().hasHeightForWidth())
        self.checkBoxActionability.setSizePolicy(sizePolicy)
        self.checkBoxActionability.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBoxActionability.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxActionability.setChecked(True)
        self.checkBoxActionability.setObjectName("checkBoxActionability")
        self.gridLayout.addWidget(self.checkBoxActionability, 0, 4, 1, 2)

        self.retranslateUi(LineEditMinimumMaximum)
        QtCore.QMetaObject.connectSlotsByName(LineEditMinimumMaximum)

    def retranslateUi(self, LineEditMinimumMaximum):
        _translate = QtCore.QCoreApplication.translate
        LineEditMinimumMaximum.setWindowTitle(_translate("LineEditMinimumMaximum", "Form"))
        self.labelFeatureMaximumValue.setText(_translate("LineEditMinimumMaximum", "Max"))
        self.labelFeatureUserValue.setText(_translate("LineEditMinimumMaximum", "Value"))
        self.labelFeatureMinimumValue.setText(_translate("LineEditMinimumMaximum", "Min"))
        self.checkBoxActionability.setText(_translate("LineEditMinimumMaximum", "actionable"))
