# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Moises\Documents\GitHub\OCEAN\ui\uiIterable\CounterfactualInterface\CounterfactualIterable\Iteration\FinalIteration\FinalIteration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FinalIteration(object):
    def setupUi(self, FinalIteration):
        FinalIteration.setObjectName("FinalIteration")
        FinalIteration.resize(586, 246)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FinalIteration)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widgetContainerCounterfactual = QtWidgets.QWidget(FinalIteration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetContainerCounterfactual.sizePolicy().hasHeightForWidth())
        self.widgetContainerCounterfactual.setSizePolicy(sizePolicy)
        self.widgetContainerCounterfactual.setStyleSheet("QWidget [objectName*=\"widgetContainerCounterfactual\"]{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.widgetContainerCounterfactual.setObjectName("widgetContainerCounterfactual")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetContainerCounterfactual)
        self.verticalLayout_3.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelCounterfactualComparison = QtWidgets.QLabel(self.widgetContainerCounterfactual)
        self.labelCounterfactualComparison.setMinimumSize(QtCore.QSize(0, 25))
        self.labelCounterfactualComparison.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelCounterfactualComparison.setText("")
        self.labelCounterfactualComparison.setObjectName("labelCounterfactualComparison")
        self.verticalLayout_3.addWidget(self.labelCounterfactualComparison)
        self.labelOriginalClass = QtWidgets.QLabel(self.widgetContainerCounterfactual)
        self.labelOriginalClass.setMinimumSize(QtCore.QSize(0, 25))
        self.labelOriginalClass.setObjectName("labelOriginalClass")
        self.verticalLayout_3.addWidget(self.labelOriginalClass)
        self.labelCounterfactualClass = QtWidgets.QLabel(self.widgetContainerCounterfactual)
        self.labelCounterfactualClass.setMinimumSize(QtCore.QSize(0, 25))
        self.labelCounterfactualClass.setObjectName("labelCounterfactualClass")
        self.verticalLayout_3.addWidget(self.labelCounterfactualClass)
        self.tableWidgetCounterfactualComparison = QtWidgets.QTableWidget(self.widgetContainerCounterfactual)
        self.tableWidgetCounterfactualComparison.setColumnCount(3)
        self.tableWidgetCounterfactualComparison.setObjectName("tableWidgetCounterfactualComparison")
        self.tableWidgetCounterfactualComparison.setRowCount(0)
        self.tableWidgetCounterfactualComparison.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetCounterfactualComparison.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidgetCounterfactualComparison.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableWidgetCounterfactualComparison)
        self.horizontalLayout.addWidget(self.widgetContainerCounterfactual)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(FinalIteration)
        QtCore.QMetaObject.connectSlotsByName(FinalIteration)

    def retranslateUi(self, FinalIteration):
        _translate = QtCore.QCoreApplication.translate
        FinalIteration.setWindowTitle(_translate("FinalIteration", "Form"))
        self.labelOriginalClass.setText(_translate("FinalIteration", "Original Class:"))
        self.labelCounterfactualClass.setText(_translate("FinalIteration", "Counterfactual Class:"))
