# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Moises\Documents\GitHub\OCEAN\ui\CounterfactualInterface\ComboboxList\ComboboxList.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComboboxList(object):
    def setupUi(self, ComboboxList):
        ComboboxList.setObjectName("ComboboxList")
        ComboboxList.resize(300, 175)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ComboboxList.sizePolicy().hasHeightForWidth())
        ComboboxList.setSizePolicy(sizePolicy)
        ComboboxList.setMaximumSize(QtCore.QSize(500, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(ComboboxList)
        self.gridLayout.setObjectName("gridLayout")
        self.labelFeatureName = QtWidgets.QLabel(ComboboxList)
        self.labelFeatureName.setMinimumSize(QtCore.QSize(0, 25))
        self.labelFeatureName.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"}")
        self.labelFeatureName.setText("")
        self.labelFeatureName.setObjectName("labelFeatureName")
        self.gridLayout.addWidget(self.labelFeatureName, 0, 0, 1, 1)
        self.checkBoxActionability = QtWidgets.QCheckBox(ComboboxList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxActionability.sizePolicy().hasHeightForWidth())
        self.checkBoxActionability.setSizePolicy(sizePolicy)
        self.checkBoxActionability.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBoxActionability.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxActionability.setChecked(True)
        self.checkBoxActionability.setObjectName("checkBoxActionability")
        self.gridLayout.addWidget(self.checkBoxActionability, 0, 1, 1, 2)
        self.comboBoxValues = QtWidgets.QComboBox(ComboboxList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxValues.sizePolicy().hasHeightForWidth())
        self.comboBoxValues.setSizePolicy(sizePolicy)
        self.comboBoxValues.setMinimumSize(QtCore.QSize(120, 25))
        self.comboBoxValues.setObjectName("comboBoxValues")
        self.gridLayout.addWidget(self.comboBoxValues, 1, 0, 1, 1)
        self.listWidgetAllowedValues = QtWidgets.QListWidget(ComboboxList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetAllowedValues.sizePolicy().hasHeightForWidth())
        self.listWidgetAllowedValues.setSizePolicy(sizePolicy)
        self.listWidgetAllowedValues.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidgetAllowedValues.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidgetAllowedValues.setObjectName("listWidgetAllowedValues")
        self.gridLayout.addWidget(self.listWidgetAllowedValues, 1, 1, 2, 2)
        self.labelSpacer = QtWidgets.QLabel(ComboboxList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSpacer.sizePolicy().hasHeightForWidth())
        self.labelSpacer.setSizePolicy(sizePolicy)
        self.labelSpacer.setMinimumSize(QtCore.QSize(0, 70))
        self.labelSpacer.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"}")
        self.labelSpacer.setText("")
        self.labelSpacer.setObjectName("labelSpacer")
        self.gridLayout.addWidget(self.labelSpacer, 2, 0, 2, 1)
        self.pushButtonCheckAll = QtWidgets.QPushButton(ComboboxList)
        self.pushButtonCheckAll.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonCheckAll.setObjectName("pushButtonCheckAll")
        self.gridLayout.addWidget(self.pushButtonCheckAll, 3, 1, 1, 1)
        self.pushButtonUncheckAll = QtWidgets.QPushButton(ComboboxList)
        self.pushButtonUncheckAll.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonUncheckAll.setObjectName("pushButtonUncheckAll")
        self.gridLayout.addWidget(self.pushButtonUncheckAll, 3, 2, 1, 1)

        self.retranslateUi(ComboboxList)
        QtCore.QMetaObject.connectSlotsByName(ComboboxList)

    def retranslateUi(self, ComboboxList):
        _translate = QtCore.QCoreApplication.translate
        ComboboxList.setWindowTitle(_translate("ComboboxList", "Form"))
        self.checkBoxActionability.setText(_translate("ComboboxList", "actionable"))
        self.pushButtonCheckAll.setText(_translate("ComboboxList", "Check All"))
        self.pushButtonUncheckAll.setText(_translate("ComboboxList", "Unckeck All"))
