# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Moises\Documents\GitHub\OCEAN\ui\CounterfactualInterface\CounterfactualInterfaceIterable.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CounterfactualInterfaceIterable(object):
    def setupUi(self, CounterfactualInterfaceIterable):
        CounterfactualInterfaceIterable.setObjectName("CounterfactualInterfaceIterable")
        CounterfactualInterfaceIterable.resize(807, 270)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CounterfactualInterfaceIterable)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetContainerDataset = QtWidgets.QWidget(CounterfactualInterfaceIterable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetContainerDataset.sizePolicy().hasHeightForWidth())
        self.widgetContainerDataset.setSizePolicy(sizePolicy)
        self.widgetContainerDataset.setMinimumSize(QtCore.QSize(540, 0))
        self.widgetContainerDataset.setMaximumSize(QtCore.QSize(540, 16777215))
        self.widgetContainerDataset.setStyleSheet("QWidget [objectName*=\"widgetContainerDataset\"]{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.widgetContainerDataset.setObjectName("widgetContainerDataset")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetContainerDataset)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSelectDatasetAndDatapoint = QtWidgets.QLabel(self.widgetContainerDataset)
        self.labelSelectDatasetAndDatapoint.setMinimumSize(QtCore.QSize(0, 25))
        self.labelSelectDatasetAndDatapoint.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelSelectDatasetAndDatapoint.setObjectName("labelSelectDatasetAndDatapoint")
        self.verticalLayout_2.addWidget(self.labelSelectDatasetAndDatapoint)
        self.widgetContainerSelectData = QtWidgets.QWidget(self.widgetContainerDataset)
        self.widgetContainerSelectData.setObjectName("widgetContainerSelectData")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetContainerSelectData)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxSelectDataset = QtWidgets.QComboBox(self.widgetContainerSelectData)
        self.comboBoxSelectDataset.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxSelectDataset.setObjectName("comboBoxSelectDataset")
        self.horizontalLayout_2.addWidget(self.comboBoxSelectDataset)
        self.pushButtonRandomPoint = QtWidgets.QPushButton(self.widgetContainerSelectData)
        self.pushButtonRandomPoint.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonRandomPoint.setObjectName("pushButtonRandomPoint")
        self.horizontalLayout_2.addWidget(self.pushButtonRandomPoint)
        self.verticalLayout_2.addWidget(self.widgetContainerSelectData)
        self.listWidgetSelectedPoint = QtWidgets.QListWidget(self.widgetContainerDataset)
        self.listWidgetSelectedPoint.setObjectName("listWidgetSelectedPoint")
        self.verticalLayout_2.addWidget(self.listWidgetSelectedPoint)
        self.pushButtonCalculateDistances = QtWidgets.QPushButton(self.widgetContainerDataset)
        self.pushButtonCalculateDistances.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonCalculateDistances.setObjectName("pushButtonCalculateDistances")
        self.verticalLayout_2.addWidget(self.pushButtonCalculateDistances)
        self.widgetContainerClass = QtWidgets.QWidget(self.widgetContainerDataset)
        self.widgetContainerClass.setObjectName("widgetContainerClass")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widgetContainerClass)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelOriginalClass = QtWidgets.QLabel(self.widgetContainerClass)
        self.labelOriginalClass.setMinimumSize(QtCore.QSize(0, 25))
        self.labelOriginalClass.setObjectName("labelOriginalClass")
        self.horizontalLayout_4.addWidget(self.labelOriginalClass)
        self.verticalLayout_2.addWidget(self.widgetContainerClass)
        self.horizontalLayout.addWidget(self.widgetContainerDataset)
        self.widgetContainerCanvas = QtWidgets.QWidget(CounterfactualInterfaceIterable)
        self.widgetContainerCanvas.setObjectName("widgetContainerCanvas")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetContainerCanvas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelSelectAxes = QtWidgets.QLabel(self.widgetContainerCanvas)
        self.labelSelectAxes.setMinimumSize(QtCore.QSize(0, 25))
        self.labelSelectAxes.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelSelectAxes.setObjectName("labelSelectAxes")
        self.verticalLayout.addWidget(self.labelSelectAxes)
        self.widgetContainerAxes = QtWidgets.QWidget(self.widgetContainerCanvas)
        self.widgetContainerAxes.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widgetContainerAxes.setObjectName("widgetContainerAxes")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widgetContainerAxes)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBoxAxisX = QtWidgets.QComboBox(self.widgetContainerAxes)
        self.comboBoxAxisX.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxAxisX.setObjectName("comboBoxAxisX")
        self.horizontalLayout_3.addWidget(self.comboBoxAxisX)
        self.comboBoxAxisY = QtWidgets.QComboBox(self.widgetContainerAxes)
        self.comboBoxAxisY.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxAxisY.setObjectName("comboBoxAxisY")
        self.horizontalLayout_3.addWidget(self.comboBoxAxisY)
        self.pushButtonUpdateGraph = QtWidgets.QPushButton(self.widgetContainerAxes)
        self.pushButtonUpdateGraph.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonUpdateGraph.setObjectName("pushButtonUpdateGraph")
        self.horizontalLayout_3.addWidget(self.pushButtonUpdateGraph)
        self.verticalLayout.addWidget(self.widgetContainerAxes)
        self.widgetCanvas = MatplotLibCanvas(self.widgetContainerCanvas)
        self.widgetCanvas.setObjectName("widgetCanvas")
        self.verticalLayout.addWidget(self.widgetCanvas)
        self.horizontalLayout.addWidget(self.widgetContainerCanvas)

        self.retranslateUi(CounterfactualInterfaceIterable)
        QtCore.QMetaObject.connectSlotsByName(CounterfactualInterfaceIterable)

    def retranslateUi(self, CounterfactualInterfaceIterable):
        _translate = QtCore.QCoreApplication.translate
        CounterfactualInterfaceIterable.setWindowTitle(_translate("CounterfactualInterfaceIterable", "Form"))
        self.labelSelectDatasetAndDatapoint.setText(_translate("CounterfactualInterfaceIterable", "Select Dataset and Datapoint"))
        self.pushButtonRandomPoint.setText(_translate("CounterfactualInterfaceIterable", "Random Point"))
        self.pushButtonCalculateDistances.setText(_translate("CounterfactualInterfaceIterable", "Calculate Distances"))
        self.labelOriginalClass.setText(_translate("CounterfactualInterfaceIterable", "Original Class:"))
        self.labelSelectAxes.setText(_translate("CounterfactualInterfaceIterable", "Select Axes"))
        self.pushButtonUpdateGraph.setText(_translate("CounterfactualInterfaceIterable", "Update Graph"))
from Canvas.MatplotLibCanvas import MatplotLibCanvas
