# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# 'OCEAN\ui\uiIterable\CounterfactualInterface\...
#       CounterfactualIterable\IterativeInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from .Dash.DashView import DashView


class UI_Iterative(object):
